version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "scottmills306"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
